<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
    <title>Document</title>

</head>
<body>

<div class="ui secondary pointing menu">
    <a class="active item">
        Home
    </a>
    <div class="right menu">
        <label class="ui item">
            Hello, <?= $first_name; ?>
        </label>

        <a href="/logout" class="ui item">
            Logout
        </a>
    </div>
</div>

</body>
</html>