<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
    <title>Document</title>

    <style type="text/css">
        body {
            background-color: #DADADA;
        }
        body > .grid {
            height: 100%;
        }
        .image {
            margin-top: -100px;
        }
        .column {
            max-width: 450px;
        }
    </style>
</head>
<body>

<div class="ui middle aligned center aligned grid">
    <div class="column">
        <h2 class="ui teal image header">
            <div class="content">
                Log-in to your account
            </div>
        </h2>
        <form class="ui large form <?= empty($error) ? '' : 'error' ?>"
              action="/login"
              method="post">
            <div class="ui stacked segment">

                <?php if(isset($error)): ?>
                <div class="ui error message">
                    <div class="header">Error</div>
                    <p><?= $error['message']; ?></p>
                </div>
                <?php endif; ?>

                <div class="field">
                    <div class="ui left icon input <?= empty($error['email']) ? '' : 'field error' ?>">
                        <i class="user icon"></i>
                        <input type="text"
                               name="email"
                               value="<?= empty($request_params['email']) ? '' : $request_params['email'] ?>"
                               placeholder="E-mail address">
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input <?= empty($error['password']) ? '' : 'field error' ?>">
                        <i class="lock icon"></i>
                        <input type="password"
                               name="password"
                               value="<?= empty($request_params['password']) ? '' : $request_params['password'] ?>"
                               placeholder="Password">
                    </div>
                </div>
                <button type="submit" class="ui fluid large teal submit button">Login</button>
            </div>

            <div class="ui error message"></div>

        </form>

        <div class="ui message">
            New to us? <a href="/sign-up">Sign Up</a>
        </div>
    </div>
</div>
</body>
</html>